
services:
  challenge:
    build:
      context: templates/win
      dockerfile: challenge.dockerfile
    volumes:
      - type: bind
        source: .
        target: /repos/helloweb3
        read_only: true
    command: sh -c "python3 -m pip install /repos/helloweb3 && python3 -m helloweb3.rpc_proxy & python3 challenge.py"
    expose:
      - 1337
      - 8545
    ports:
      - "1337:1337"
      - "8545:8545"
    environment:
      FLAG: ctf{o_no_access_control}
      TIMEOUT: 60 # seconds
      POW_DIFFICULTY: 22 # bits
      PUBLIC_HOST: "http://challenge:8545"

  solve:
    build:
      context: templates/win
      dockerfile: solve.dockerfile
    command: sh -c "sleep 5; python3 solve.py HOST=challenge"
