services:
  challenge:
    build:
      context: .
      dockerfile: challenge.dockerfile
    command: sh -c "python3 -m helloweb3.rpc_proxy & python3 challenge.py"
    expose:
      - 1337
      - 8545
    ports:
      - "1337:1337"
      - "8545:8545"
    environment:
      FLAG: ctf{o_no_access_control}
      TIMEOUT: 60 # seconds
      POW_DIFFICULTY: 22 # bits
      PUBLIC_HOST: "http://challenge:8545"
      HELLOWEB3_URL: # put your repository here
