services:
  challenge:
    build:
      context: .
      dockerfile: challenge.dockerfile
      args:
        HELLOWEB3: git+https://github.com/bbjubjub2494/helloweb3
    command: sh -c "python3 -m helloweb3.rpc_proxy & python3 challenge.py"
    expose:
      - 1337
      - 8545
    ports:
      - "1337:1337"
      - "8545:8545"
    environment:
      FLAG: ctf{o_no_access_control}
      TIMEOUT: 60 # seconds
      POW_DIFFICULTY: 22 # bits
      PUBLIC_HOST: "http://challenge:8545"

  solve:
    build:
      context: .
      dockerfile: solve.dockerfile
    command: sh -c "sleep 5; python3 solve.py HOST=challenge"
